### ISSUE TITLE
Support for 3090 Ti

### ISSUE THREAD

**Issue by shivams** [olealgoritme/gddr6#27]
I have two 3090 Ti FEs in my workstation and was trying to use this tool but it reports "No compatible GPU found". I see that `3090 Ti` is not in the list of supported GPUs. Can we make it work for `3090 Ti`?

**Comment by olealgoritme** [comment]
Check your device IDs. Check the code. If the device IDs are missing from the device table, just add them.

Let me know how you get a long. I can add them for you if you need assistance, just need the device IDs.

**Comment by shivams** [comment]
Okay. Thank you. I added the device ID for 3090 Ti and it's working now. I have also made a pull request.
