### ISSUE TITLE
Temperature for RTX A2000

### ISSUE THREAD

**Issue by felix303** [olealgoritme/gddr6#3]
Is there a chance to add details for RTX A2000 (GA106),6GB, GDDR6 ?
These are the Device ID details. No idea which offset to set.

$> lspci -nn |grep NVIDIA
06:10.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [RTX A2000] [10de:2531] (rev a1)
06:11.0 Audio device [0403]: NVIDIA Corporation Device [10de:228e] (rev a1)

Thank you for you help.

**Comment by olealgoritme** [comment]
@felix303 
I could help you find the details for the RTX A2000.
Hit me up on discord. 
```
olealgo#1020 @ GPU Unlocking channel 
https://discord.gg/qnRs4pMtND

**Comment by olealgoritme** [comment]
A2000 supported added. Closing.
