### ISSUE TITLE
Only shows one GPU temp when multiple GPUs in system

### ISSUE THREAD

**Issue by m4gr4th34** [olealgoritme/gddr6#4]
Hi, really sorry to ask for more, but would it be possible to observe the vram temps of multiple gpus?  In my dual gpu setup (for ai/ml work), it appears if there is gpu 0 and gpu 1, it only pulls the vram temps of gpu 1.  I will look at the code and see if I can make the changes myself, but thought I might as well plug the request in here as well.  Thanks in advance, in case you have time to figure it out!

**Comment by jamarju** [comment]
See https://github.com/olealgoritme/gddr6/pull/5

**Comment by olealgoritme** [comment]
Solved by #5. Nice work :smiley: :rocket:
